---
seed: 1984

num_workers: 4
experiment_name: "2020-11-20"

generator:
  type: high_resolution_image_inpainting_gan.inpainting_network.GatedGenerator
  norm: none
  activation: elu

discriminator:
  type: high_resolution_image_inpainting_gan.inpainting_network.PatchDiscriminator

trainer:
  type: pytorch_lightning.Trainer
  gpus: 4
  max_epochs: 10
  distributed_backend: ddp
  progress_bar_refresh_rate: 1
  benchmark: True
  precision: 16
  gradient_clip_val: 5.0
  num_sanity_val_steps: 1
  sync_batchnorm: True

scheduler_generator:
  type: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 10
  T_mult: 2

scheduler_discriminator:
  type: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 10
  T_mult: 2

train_parameters:
  batch_size: 8

checkpoint_callback:
  type: pytorch_lightning.callbacks.ModelCheckpoint
  filepath: "2020-11-20"
  verbose: True
  save_top_k: -1

optimizer_generator:
  type: torch.optim.Adam
  lr: 0.0001

optimizer_discriminator:
  type: torch.optim.Adam
  lr: 0.0004

loss_weights:
  mask_l1: 128
  mask_l2: 256
  gan: 1
  hinge: 1
  perceptual: 100

train_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.SmallestMaxSize
        max_size: 512
        always_apply: False
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.RandomCrop
        width: 512
        height: 512
        always_apply: False
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.HorizontalFlip
        always_apply: False
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0
          - 0
          - 0
        p: 1
        std:
          - 1
          - 1
          - 1
